/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/qOdir7PRJLv
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogBody, DialogFooter, DialogClose } from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

export function Portfolios() {
  return (
    <div className="flex flex-col min-h-screen bg-background text-foreground">
      <header className="sticky top-0 z-50 bg-background/90 backdrop-blur">
        <div className="container mx-auto flex h-16 max-w-6xl items-center justify-between px-4 sm:px-6">
          <div className="flex items-center gap-4">
            <Link href="#" prefetch={false}>
              <div className="flex items-center gap-2">
                <MountainIcon className="h-6 w-6" />
                <span className="text-lg font-bold">John Doe</span>
              </div>
            </Link>
          </div>
          <nav className="hidden space-x-4 md:flex">
            <Link href="#" className="text-sm font-medium hover:text-primary transition-colors" prefetch={false}>
              About
            </Link>
            <Link href="#" className="text-sm font-medium hover:text-primary transition-colors" prefetch={false}>
              Skills
            </Link>
            <Link href="#" className="text-sm font-medium hover:text-primary transition-colors" prefetch={false}>
              Projects
            </Link>
            <Link href="#" className="text-sm font-medium hover:text-primary transition-colors" prefetch={false}>
              Blogs
            </Link>
          </nav>
          <div className="flex items-center gap-4">
            <Link
              href="#"
              target="_blank"
              rel="noopener noreferrer"
              className="text-muted-foreground hover:text-primary transition-colors"
              prefetch={false}
            >
              <TwitterIcon className="h-5 w-5" />
            </Link>
            <Link
              href="#"
              target="_blank"
              rel="noopener noreferrer"
              className="text-muted-foreground hover:text-primary transition-colors"
              prefetch={false}
            >
              <LinkedinIcon className="h-5 w-5" />
            </Link>
            <Link
              href="#"
              target="_blank"
              rel="noopener noreferrer"
              className="text-muted-foreground hover:text-primary transition-colors"
              prefetch={false}
            >
              <GitlabIcon className="h-5 w-5" />
            </Link>
          </div>
        </div>
      </header>
      <main className="flex-1">
        <section id="about" className="py-16 sm:py-24">
          <div className="container mx-auto max-w-6xl px-4 sm:px-6">
            <div className="grid grid-cols-1 gap-8 md:grid-cols-2">
              <div>
                <h1 className="text-4xl font-bold">John Doe</h1>
                <h2 className="text-2xl font-medium text-muted-foreground">Data Scientist</h2>
                <p className="mt-4 text-muted-foreground">
                  I am a passionate data scientist with a strong background in machine learning, data analysis, and
                  problem-solving. I thrive on using data-driven insights to drive business decisions and create
                  innovative solutions.
                </p>
              </div>
              <div className="flex items-center justify-end">
                <div className="space-x-4">
                  <Link
                    href="#"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-muted-foreground hover:text-primary transition-colors"
                    prefetch={false}
                  >
                    <TwitterIcon className="h-6 w-6" />
                  </Link>
                  <Link
                    href="#"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-muted-foreground hover:text-primary transition-colors"
                    prefetch={false}
                  >
                    <LinkedinIcon className="h-6 w-6" />
                  </Link>
                  <Link
                    href="#"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-muted-foreground hover:text-primary transition-colors"
                    prefetch={false}
                  >
                    <GitlabIcon className="h-6 w-6" />
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section id="skills" className="bg-muted py-16 sm:py-24">
          <div className="container mx-auto max-w-6xl px-4 sm:px-6">
            <h2 className="mb-8 text-3xl font-bold">Technical Skills</h2>
            <div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3">
              <div>
                <h3 className="mb-4 text-xl font-bold">Programming Languages</h3>
                <ul className="space-y-2">
                  <li>Python</li>
                  <li>R</li>
                  <li>SQL</li>
                  <li>JavaScript</li>
                </ul>
              </div>
              <div>
                <h3 className="mb-4 text-xl font-bold">Data Analysis Tools</h3>
                <ul className="space-y-2">
                  <li>Pandas</li>
                  <li>NumPy</li>
                  <li>Matplotlib</li>
                  <li>Tableau</li>
                </ul>
              </div>
              <div>
                <h3 className="mb-4 text-xl font-bold">Machine Learning Frameworks</h3>
                <ul className="space-y-2">
                  <li>TensorFlow</li>
                  <li>Scikit-learn</li>
                  <li>PyTorch</li>
                  <li>XGBoost</li>
                </ul>
              </div>
            </div>
          </div>
        </section>
        <section id="projects" className="py-16 sm:py-24">
          <div className="container mx-auto max-w-6xl px-4 sm:px-6">
            <h2 className="mb-8 text-3xl font-bold">Projects</h2>
            <div className="grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">
              <Link
                href="#"
                className="group overflow-hidden rounded-lg shadow-lg transition-all hover:-translate-y-1 hover:shadow-xl"
                prefetch={false}
              >
                <img
                  src="/placeholder.svg"
                  alt="Project 1"
                  width={400}
                  height={300}
                  className="h-48 w-full object-cover object-center transition-all group-hover:scale-105"
                  style={{ aspectRatio: "400/300", objectFit: "cover" }}
                />
                <div className="bg-background p-4">
                  <h3 className="text-lg font-bold">Project 1</h3>
                  <p className="text-muted-foreground">
                    A detailed analysis of customer churn using machine learning techniques.
                  </p>
                </div>
              </Link>
              <Link
                href="#"
                className="group overflow-hidden rounded-lg shadow-lg transition-all hover:-translate-y-1 hover:shadow-xl"
                prefetch={false}
              >
                <img
                  src="/placeholder.svg"
                  alt="Project 2"
                  width={400}
                  height={300}
                  className="h-48 w-full object-cover object-center transition-all group-hover:scale-105"
                  style={{ aspectRatio: "400/300", objectFit: "cover" }}
                />
                <div className="bg-background p-4">
                  <h3 className="text-lg font-bold">Project 2</h3>
                  <p className="text-muted-foreground">
                    Predictive modeling for sales forecasting using time series analysis.
                  </p>
                </div>
              </Link>
              <Link
                href="#"
                className="group overflow-hidden rounded-lg shadow-lg transition-all hover:-translate-y-1 hover:shadow-xl"
                prefetch={false}
              >
                <img
                  src="/placeholder.svg"
                  alt="Project 3"
                  width={400}
                  height={300}
                  className="h-48 w-full object-cover object-center transition-all group-hover:scale-105"
                  style={{ aspectRatio: "400/300", objectFit: "cover" }}
                />
                <div className="bg-background p-4">
                  <h3 className="text-lg font-bold">Project 3</h3>
                  <p className="text-muted-foreground">
                    Developing a recommendation system for an e-commerce platform.
                  </p>
                </div>
              </Link>
            </div>
          </div>
        </section>
        <section id="blogs" className="bg-muted py-16 sm:py-24">
          <div className="container mx-auto max-w-6xl px-4 sm:px-6">
            <h2 className="mb-8 text-3xl font-bold">Blogs</h2>
            <div className="grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">
              <Link
                href="#"
                className="group overflow-hidden rounded-lg bg-background shadow-lg transition-all hover:-translate-y-1 hover:shadow-xl"
                prefetch={false}
              >
                <div className="p-4">
                  <h3 className="text-lg font-bold">Blog Post 1</h3>
                  <p className="text-muted-foreground">
                    Exploring the latest advancements in natural language processing for text analysis.
                  </p>
                </div>
              </Link>
              <Link
                href="#"
                className="group overflow-hidden rounded-lg bg-background shadow-lg transition-all hover:-translate-y-1 hover:shadow-xl"
                prefetch={false}
              >
                <div className="p-4">
                  <h3 className="text-lg font-bold">Blog Post 2</h3>
                  <p className="text-muted-foreground">
                    Applying deep learning techniques to computer vision problems.
                  </p>
                </div>
              </Link>
              <Link
                href="#"
                className="group overflow-hidden rounded-lg bg-background shadow-lg transition-all hover:-translate-y-1 hover:shadow-xl"
                prefetch={false}
              >
                <div className="p-4">
                  <h3 className="text-lg font-bold">Blog Post 3</h3>
                  <p className="text-muted-foreground">
                    Optimizing data pipelines for efficient and scalable data processing.
                  </p>
                </div>
              </Link>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-muted py-8">
        <div className="container mx-auto max-w-6xl px-4 sm:px-6 flex justify-between items-center">
          <p className="text-muted-foreground">&copy; 2023 John Doe</p>
          <div className="flex items-center gap-4">
            <Link href="#" className="text-muted-foreground hover:text-primary transition-colors" prefetch={false}>
              <MailIcon className="h-5 w-5" />
            </Link>
            <Dialog>
              <DialogTrigger asChild>
                <Button variant="ghost" className="text-muted-foreground hover:text-primary transition-colors">
                  <WebcamIcon className="h-5 w-5" />
                </Button>
              </DialogTrigger>
              <DialogContent>
                <DialogHeader>
                  <DialogTitle>Contact John Doe</DialogTitle>
                  <DialogDescription>Feel free to reach out with any questions or inquiries.</DialogDescription>
                </DialogHeader>
                <div>
                  <form>
                    <div className="grid gap-4">
                      <Input label="Name" />
                      <Input label="Email" type="email" />
                      <Textarea label="Message" />
                    </div>
                  </form>
                </div>
                <DialogFooter>
                  <div>
                    <Button>Send Message</Button>
                  </div>
                </DialogFooter>
              </DialogContent>
            </Dialog>
          </div>
        </div>
      </footer>
    </div>
  )
}

function GitlabIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 13.29-3.33-10a.42.42 0 0 0-.14-.18.38.38 0 0 0-.22-.11.39.39 0 0 0-.23.07.42.42 0 0 0-.14.18l-2.26 6.67H8.32L6.1 3.26a.42.42 0 0 0-.1-.18.38.38 0 0 0-.26-.08.39.39 0 0 0-.23.07.42.42 0 0 0-.14.18L2 13.29a.74.74 0 0 0 .27.83L12 21l9.69-6.88a.71.71 0 0 0 .31-.83Z" />
    </svg>
  )
}


function LinkedinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  )
}


function MailIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  )
}


function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function TwitterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}


function WebcamIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="10" r="8" />
      <circle cx="12" cy="10" r="3" />
      <path d="M7 22h10" />
      <path d="M12 22v-4" />
    </svg>
  )
}
